
services:
  database:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:  my-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    container_name: backend
    image: zorochan/backend:latest
    ports:
     - "3500:3500"
    networks:
      - my-network
    environment:
      host: database
      user: root
      password: root
      database: my-db
    depends_on:
      database:
        condition: service_healthy
  frontend:
    container_name: frontend
    image: zorochan/frontend:latest
    networks:
      - my-network
    ports:
      - "80:80"
    
    depends_on:
      backend:  
        condition: service_started

    environment:
      NODE_ENV: production

networks:
  my-network:


volumes:
  mysql-data: